### ISSUE TITLE
Safari starting up on refresh

### ISSUE THREAD

**Issue by waldbach** [gcollazo/BrowserRefresh-Sublime#68]
There seems to be a bug where Safari (on a Mac) starts up when it's not running on refresh. The currently running browser (in my case Firefox Developer Edition) is refreshing after launching Safari.
For now, as a temporary workaround, I commented out Safari, since I don't use that for testing.

In `BrowserRefresh.py` I commented out:
```python
        elif browser_name == 'all':
            refresher.chrome()
           # refresher.safari()
            refresher.firefox()
            refresher.opera()
```

**Comment by charlesmudy** [comment]
:+1:

**Comment by imlazyone** [comment]
I guess the reason is that you have some applications like Slack opened - which is using the Safari browser. So if your config is 
```
"browser_name" : "all"
```
It will also open a Safari window and try to refresh.

I specified a `browser_name` in sublime settings and it's ok now.
```
"browser_name" : "Google Chrome"
```

**Comment by chrleon** [comment]
How would I go about making the plugin refresh both chrome and safari, if I'm not setting the prefs to "all"

**Comment by gcollazo** [comment]
@chrleon The plugin is supposed to refresh all open browsers when set to "all". Currently it seems that Safari is starting on refresh because the plugin is wrongfully detecting Safari running when it's not.

There's no way to specify 2 specific browser to refresh but that seems like a great fix for this particular issue.

I propose removing the "all" option and replacing the "browser_name" option for something like this

```json
"browsers": ["chrome", "firefox"]
```

This way you could recreate the "all" option by listing all the browsers you want and we could remove the running browser logic from the plugin.

**Comment by chrleon** [comment]
Yes I tried that, but it still fired Safari. I'll have a look again, and
see if I (likely) messed something up, before I posted.


- christian

---
Either we are alone in the Universe or we are not. Both are equally
terrifying. – A.C Clark

**Comment by gcollazo** [comment]
I'm preparing a fix for this... will publish later today

**Comment by gcollazo** [comment]
Just pushed the update, it should be available soon. Make sure you update your settings.
